# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 320)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.connectToHomeBtn = QtWidgets.QPushButton(self.centralwidget)
        self.connectToHomeBtn.setObjectName("connectToHomeBtn")
        self.horizontalLayout_3.addWidget(self.connectToHomeBtn)
        self.connectToHotspotBtn = QtWidgets.QPushButton(self.centralwidget)
        self.connectToHotspotBtn.setObjectName("connectToHotspotBtn")
        self.horizontalLayout_3.addWidget(self.connectToHotspotBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.uploadBtn = QtWidgets.QPushButton(self.centralwidget)
        self.uploadBtn.setObjectName("uploadBtn")
        self.verticalLayout_2.addWidget(self.uploadBtn)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.connectionStatus = QtWidgets.QLabel(self.centralwidget)
        self.connectionStatus.setObjectName("connectionStatus")
        self.horizontalLayout_4.addWidget(self.connectionStatus)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.uploadStatus = QtWidgets.QLabel(self.centralwidget)
        self.uploadStatus.setObjectName("uploadStatus")
        self.horizontalLayout_5.addWidget(self.uploadStatus)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dashcam Upload"))
        self.connectToHomeBtn.setText(_translate("MainWindow", "Connect To Home WiFi"))
        self.connectToHotspotBtn.setText(_translate("MainWindow", "Connect To Hotspot"))
        self.uploadBtn.setText(_translate("MainWindow", "Upload"))
        self.label.setText(_translate("MainWindow", "Connection Status:"))
        self.connectionStatus.setText(_translate("MainWindow", "Disconnected"))
        self.label_3.setText(_translate("MainWindow", "Upload Status:"))
        self.uploadStatus.setText(_translate("MainWindow", "Not Uploading"))
